#!/usr/bin/env python3
"""
DMAF Repository Bootstrap v1.0

Run this from the root of your empty DMAF GitHub repository:

    python bootstrap_dmaf.py
"""

from pathlib import Path
from datetime import date

VERSION = "1.0.0"
AUTHOR = "Ed Franc"
TARGET_PLATFORM = "Azure Databricks"

FOLDERS = [
    "00-Governance/Charter",
    "00-Governance/Guiding-Principles",
    "00-Governance/Governance",
    "00-Governance/Roadmap",
    "00-Governance/Release-Notes",
    "00-Governance/Baseline-Register",

    "01-Framework/Practice-Domains",
    "01-Framework/Lifecycle",
    "01-Framework/Cross-Cutting-Capabilities",
    "01-Framework/Meta-Model",
    "01-Framework/Knowledge-Graph",
    "01-Framework/Taxonomy",
    "01-Framework/Capability-Model",

    "02-Playbook/Discovery",
    "02-Playbook/Assessment",
    "02-Playbook/Architecture",
    "02-Playbook/Migration-Factory",
    "02-Playbook/Validation",
    "02-Playbook/Executive-Advisory",
    "02-Playbook/Platform-Adoption",

    "03-Assets/Executive",
    "03-Assets/Discovery",
    "03-Assets/Assessment",
    "03-Assets/Architecture",
    "03-Assets/Migration-Factory",
    "03-Assets/Validation",
    "03-Assets/Industry",
    "03-Assets/Templates",
    "03-Assets/Workshops",

    "04-Reference-Architectures/Banking",
    "04-Reference-Architectures/Insurance",
    "04-Reference-Architectures/Retail",
    "04-Reference-Architectures/Government",
    "04-Reference-Architectures/Generic",

    "05-Workbench/docs",
    "05-Workbench/frontend",
    "05-Workbench/backend",
    "05-Workbench/prompts",
    "05-Workbench/agents",
    "05-Workbench/knowledge",

    "06-Research/Databricks",
    "06-Research/Azure",
    "06-Research/AI",
    "06-Research/Competitors",
    "06-Research/Industry",

    "07-Releases/Release-1.0",
    "07-Releases/Release-2.0",
    "07-Releases/Archive",

    "99-Archive",
    ".github/ISSUE_TEMPLATE",
    ".github/workflows",
]

def write_file(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content.strip() + "\n", encoding="utf-8")

def folder_readme(folder_name: str) -> str:
    return f"""# {folder_name}

## Purpose

This folder contains DMAF assets related to `{folder_name}`.

## Expected Contents

- Markdown documents
- Templates
- Diagrams
- Workbooks
- Supporting references

## Contribution Guidance

Add new files only when they support a DMAF practice domain, lifecycle stage, or reusable capability.

Each major artifact should include metadata where applicable.
"""

TOP_LEVEL_README = f"""# DMAF — Databricks Modernization Advisory Framework

DMAF is a Databricks-first enterprise modernization advisory framework for helping clients move from legacy data platforms to scalable, governed, cloud-native Databricks Lakehouse architectures.

## Purpose

This repository contains the source of truth for DMAF, including framework governance, guiding principles, practice domains, lifecycle models, capability models, playbook content, reusable assets, reference architectures, industry packs, and Modernization Intelligence Workbench assets.

## Strategic Positioning

DMAF is source-platform adaptive and Databricks-first.

It can support modernization from Informatica PowerCenter, mainframe, SSIS, DataStage, Hadoop, Teradata, Oracle ETL, and other legacy data platforms while primarily optimizing for Azure Databricks, Delta Lake, Unity Catalog, Lakehouse architecture, cloud-native data engineering, and enterprise governance.

## Repository Status

Initial repository baseline generated by `bootstrap_dmaf.py`.

Version: {VERSION}  
Owner: {AUTHOR}  
Target Platform: {TARGET_PLATFORM}  
Created: {date.today().isoformat()}
"""

CONTRIBUTING = """# Contributing to DMAF

DMAF should be managed like a product, not a one-time project.

## Contribution Rules

Every new artifact should answer:

1. Which DMAF practice domain does it support?
2. Which lifecycle stage uses it?
3. Which guiding principle does it reinforce?
4. Which reusable asset or capability does it improve?
5. Can it be reused across engagements?

## Preferred Formats

- Markdown for documents
- Draw.io for editable diagrams
- PowerPoint for client-facing decks
- Excel for workbooks and calculators
- HTML/CSS/JS for lightweight prototypes
"""

CHANGELOG = f"""# Changelog

## {VERSION} — Repository Foundation

Date: {date.today().isoformat()}

### Added

- Initial DMAF repository structure
- Governance folders
- Framework folders
- Playbook folders
- Asset library folders
- Reference architecture folders
- Workbench folders
- Research folders
- Release folders
- GitHub issue and pull request templates
"""

GITIGNORE = """# OS files
.DS_Store
Thumbs.db

# Python
__pycache__/
*.pyc
.venv/
venv/

# Node
node_modules/
dist/
build/

# Logs
*.log

# Temporary files
*.tmp
*.bak

# Local environment
.env
.env.local
"""

LICENSE = """Copyright (c) 2026

All rights reserved.

This repository contains internal consulting intellectual property for the Databricks Modernization Advisory Framework (DMAF).

Do not distribute externally without authorization.
"""

ASSET_METADATA_TEMPLATE = """---
asset_id: DMAF-XXX-000
title: Replace with asset title
status: Draft
version: 0.1.0
owner: Replace with owner
release: Release-1.0

practice_domain:
  - Replace with DMAF practice domain

capability:
  - Replace with capability

lifecycle_stage:
  - Replace with lifecycle stage

cross_cutting_capabilities:
  - Governance & Security
  - Risk & Compliance
  - FinOps & Cost Optimization
  - AI Enablement
  - Automation
  - Knowledge Management
  - Reusable Accelerators

guiding_principles:
  - Replace with applicable guiding principle

dependencies:
  - Replace with related assets

last_updated: YYYY-MM-DD
---

# Asset Title

## Purpose

Describe why this asset exists.

## Audience

Describe who uses this asset.

## Usage

Describe when and how this asset should be used.

## Content

Add asset content here.
"""

ISSUE_TEMPLATE = """---
name: DMAF Asset Request
about: Request a new DMAF asset, enhancement, or framework update
title: "[ASSET] "
labels: asset
assignees: ""
---

## Request Type

- [ ] New asset
- [ ] Enhancement
- [ ] Framework update
- [ ] Research item
- [ ] Diagram
- [ ] Workbench feature

## Description

Describe the requested item.

## DMAF Mapping

Practice Domain:

Lifecycle Stage:

Guiding Principle:

Release Target:

## Acceptance Criteria

- [ ] Clearly defined purpose
- [ ] Reusable across engagements
- [ ] Aligned to DMAF standards
- [ ] Reviewed and approved
"""

PR_TEMPLATE = """# DMAF Pull Request

## Summary

Describe the change.

## DMAF Mapping

Practice Domain:

Lifecycle Stage:

Guiding Principle:

Release:

## Checklist

- [ ] Naming convention followed
- [ ] Metadata included where applicable
- [ ] Content reviewed for clarity
- [ ] No confidential client information included
- [ ] Artifact is reusable
"""

CODEOWNERS = """# DMAF Code Owners
# Update with real GitHub usernames when available.

* @owner
"""

CLAUDE = """# CLAUDE.md

This folder will contain working instructions for the DMAF Modernization Intelligence Workbench.

The Workbench should operationalize DMAF by helping users ingest messy engagement inputs, interpret modernization context, generate recommendations, and produce consulting-grade advisory outputs.
"""

def main():
    root = Path.cwd()

    write_file(root / "README.md", TOP_LEVEL_README)
    write_file(root / "CONTRIBUTING.md", CONTRIBUTING)
    write_file(root / "CHANGELOG.md", CHANGELOG)
    write_file(root / ".gitignore", GITIGNORE)
    write_file(root / "LICENSE", LICENSE)

    for folder in FOLDERS:
        p = root / folder
        p.mkdir(parents=True, exist_ok=True)
        write_file(p / "README.md", folder_readme(folder))
        write_file(p / ".gitkeep", "")

    write_file(root / "03-Assets/Templates/asset-metadata-template.md", ASSET_METADATA_TEMPLATE)
    write_file(root / ".github/ISSUE_TEMPLATE/dmaf-asset-request.md", ISSUE_TEMPLATE)
    write_file(root / ".github/PULL_REQUEST_TEMPLATE.md", PR_TEMPLATE)
    write_file(root / ".github/CODEOWNERS", CODEOWNERS)
    write_file(root / "05-Workbench/CLAUDE.md", CLAUDE)

    print("DMAF repository bootstrap complete.")
    print(f"Version: {VERSION}")
    print(f"Root: {root}")

if __name__ == "__main__":
    main()
